# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [9]:
from typing import List
import re

def tokenize_words(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    return re.split(r'\s+', text)

def tokenize_sentence(text: str) -> list:
    """Tokenize text into words using regex.

    Parameters
    ----------
    text: str
            Text to be tokenized

    Returns
    -------
    List[str]
            List containing words tokenized from text

    """
    pattern = r'(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?|\!)\s'
    return re.split(pattern, text)

text = (
    "Here we go again. I was supposed to add this text later. "
    "Well, it's 10.p.m. here, and I'm actually having fun making this course. :o "
    "I hope you are getting along fine with this presentation, I really did try. "
    "And one last sentence, just so you can test you tokenizers better."
)

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', 'I was supposed to add this text later.', "Well, it's 10.p.m. here, and I'm actually having fun making this course.", ':o I hope you are getting along fine with this presentation, I really did try.', 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again.', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later.', 'Well,', "it's", '10.p.m.', 'here,', 'and', "I'm", 'actually', 'having', 'fun', 'making', 'this', 'course.', ':o', 'I', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation,', 'I', 'really', 'did', 'try.', 'And', 'one', 'last', 'sentence,', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better.']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [6]:
import nltk

In [12]:
from nltk import pos_tag

In [13]:
file = open("../datasets/trump.txt", "r",encoding="utf-8") 
trump = file.read()
words = tokenize_words(trump)

# fill the gap and imports
tags = pos_tag(words)
tags

[('Thank', 'NNP'),
 ('you', 'PRP'),
 ('very', 'RB'),
 ('much.', 'VBP'),
 ('Mr.', 'NNP'),
 ('Speaker,', 'NNP'),
 ('Mr.', 'NNP'),
 ('Vice', 'NNP'),
 ('President,', 'NNP'),
 ('Members', 'NNP'),
 ('of', 'IN'),
 ('Congress,', 'NNP'),
 ('the', 'DT'),
 ('First', 'NNP'),
 ('Lady', 'NNP'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('United', 'NNP'),
 ('States,', 'NNP'),
 ('and', 'CC'),
 ('citizens', 'NNS'),
 ('of', 'IN'),
 ('America:', 'NNP'),
 ('Tonight,', 'NNP'),
 ('as', 'IN'),
 ('we', 'PRP'),
 ('mark', 'VBP'),
 ('the', 'DT'),
 ('conclusion', 'NN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ('celebration', 'NN'),
 ('of', 'IN'),
 ('Black', 'NNP'),
 ('History', 'NNP'),
 ('Month,', 'NNP'),
 ('we', 'PRP'),
 ('are', 'VBP'),
 ('reminded', 'VBN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ("Nation's", 'NNP'),
 ('path', 'NN'),
 ('towards', 'NNS'),
 ('civil', 'JJ'),
 ('rights', 'NNS'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('work', 'NN'),
 ('that', 'WDT'),
 ('still', 'RB'),
 ('remains', 'VBZ'),
 ('to', 'TO'),
 ('be', 'VB'),
 ('done

## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [6]:
import spacy
spacy.cli.download("en_core_web_sm")

file = open("../datasets/trump.txt", "r",encoding='utf-8') 
trump = file.read() 

### here comes your code
nlp = spacy.load("en_core_web_sm")
processed_text = nlp(trump)

# Get the last 10 sentences
sentences = list(processed_text.sents)
last_10_sentences = sentences[-10:]

for i, sentence in enumerate(last_10_sentences, 1):
    nouns = [token.text for token in sentence if token.pos_ == "NOUN"]
    print("Sentence "+str(i)+": "+str(sentence))
    print("Nouns: "+str(nouns))
    print()

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Sentence 1: When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.
Nouns: ['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']

Sentence 2: The time for small thinking is over.
Nouns: ['time', 'thinking']

Sentence 3: The time for trivial fights is behind us.
Nouns: ['time', 'fights']

Sentence 4: We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.


Nouns: ['courage', 'dreams', 'hearts', 'bravery', 

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [10]:
import numpy as np
import spacy

class BagOfWords:
    """Basic BoW implementation."""
    
    __nlp = spacy.load("en_core_web_sm")
    __bow_list = []
    
    # your code goes maybe also here
    def preprocess_text(self, text):
        text = text.lower()
        cleaned = re.sub(r'[\W_]+', ' ', text)

        return cleaned.strip()    
    
    def fit_transform(self, corpus: list):
        """Transform list of strings into BoW array.

        Parameters
        ----------
        corpus: List[str]
                Corpus of texts to be transforrmed

        Returns
        -------
        np.array
                Matrix representation of BoW

        """
        cleaned_texts = [self.preprocess_text(text) for text in corpus]
        tokenized_corpus = [tokenize_words(text) for text in cleaned_texts]

        vocab = sorted(set(word for doc in tokenized_corpus for word in doc))
        self.__bow_list = vocab

        bow_matrix = np.zeros((len(corpus), len(vocab)), dtype=int)
        for i, doc in enumerate(tokenized_corpus):
            for word in doc:
                if word in vocab:
                    j = vocab.index(word)
                    bow_matrix[i][j] += 1      
        return bow_matrix
      

    def get_feature_names(self) -> list:
        """Return words corresponding to columns of matrix.

        Returns
        -------
        List[str]
                Words being transformed by fit function

        """   
        # your code goes here
        return self.__bow_list

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[0 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 1]
 [1 0 0 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 2 1 0 0 1 0 1 0 0]]


31

In [11]:
print(vectorizer.get_feature_names())

['a', 'as', 'bag', 'based', 'below', 'can', 'counting', 'document', 'documents', 'gives', 'is', 'matrix', 'most', 'multiple', 'occur', 'occurences', 'of', 'on', 'once', 'only', 'pretty', 'really', 'see', 'sparse', 'the', 'third', 'this', 'throughout', 'us', 'words', 'you']


## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [13]:
from nltk.book import *

wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1;

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):]);
    choices = counts[token_seq].items();

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [16]:
import random

In [18]:
def clean_generated(text):
    text = re.sub(r'\s+([.!?])', r'\1', text)
    sentences = re.split(r'(?<=[.!?])\s+', text)
    capitalized = [s.strip().capitalize() for s in sentences]

    return ' '.join(capitalized)

N=5 # fix it for other value of N

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq="We have to be"

counts = ngram_freqs(ngrams)

if start_seq is None: start_seq = random.choice(list(counts.keys()))
generated = start_seq.lower();

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

generated = clean_generated(generated)

print(generated)

We have to be more like the department store not the boutique. Iras. Sharedata inc. Said 0 it will resubmit the registration 0 to cover only the 2.3 million warrants each exercisable for the purchase of one common share. Currently sharedata has about 4.1 million common shares outstanding.
